apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: explorer
    workspace: boxyexplorer/
#  - imageName: wallet
#    workspace: wallet/
deploy:
  kubectl:
    manifests:
      - ./k8s-spec/*